import type { Metadata } from 'next'
import { ThemeProvider } from "@/components/theme-provider"
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import { Toaster } from '@/components/ui/sonner'
import AppProvider from './AppProvider'
import { cookies } from 'next/headers'

// const roboto = Roboto({ subsets: ['vietnamese'], weight: ['100', '300'] })
const inter = Inter({subsets: ['vietnamese']})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {

  const cookieStore = await cookies()
  const sessionToken = cookieStore.get('sessionToken')
  
  return (
    <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className}`} suppressHydrationWarning>
          <Toaster/>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AppProvider initialSessionToken={sessionToken?.value}>
              <Header/>
              {children}
            </AppProvider>
          </ThemeProvider>
        </body>
    </html>
  )
}
